version: '3.8'

services:
  # News Agent Python Backend
  backend:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./:/app
    command: gunicorn --bind 0.0.0.0:5000 --workers 4 --reload --timeout 120 news_agent_python:app

  # Optional: Frontend service (if needed in the future)
  # frontend:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./frontend:/usr/share/nginx/html
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - backend

  # Optional: Redis for enhanced caching (if needed in the future)
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data

# Optional: Volume for Redis data (if Redis is enabled)
# volumes:
#   redis-data: